//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiSegura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Error
    {
        public int ERR_CODIGO { get; set; }
        public int USU_CODIGO { get; set; }
        public System.DateTime ERR_FEC_HORA { get; set; }
        public string ERR_FUENTE { get; set; }
        public string ERR_NUMERO { get; set; }
        public string ERR_DESCRIPCION { get; set; }
        public string ERR_VISTA { get; set; }
        public string ERR_ACCION { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
